name: Firebase Deployment

on:
  pull_request:
    branches:
      - main
      - test

jobs:
  build_and_deploy_prod:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    env:
      VITE_FIREBASE_API_KEY: 'AIzaSyApjz_Y0SaYwath6x_ZuJL_BPk01PA7q7w'
      VITE_FIREBASE_AUTH_DOMAIN: 'prod-trailer-rental.firebaseapp.com'
      VITE_FIREBASE_PROJECT_ID: 'prod-trailer-rental'
      VITE_FIREBASE_STORAGE_BUCKET: 'prod-trailer-rental.appspot.com'
      VITE_FIREBASE_MESSAGING_SENDER_ID: '268717464417'
      VITE_FIREBASE_APP_ID: '1:268717464417:web:8d81dd679f4c39deb38320'
      VITE_FIREBASE_MEASUREMENT_ID: 'G-PR3XE5RXLT'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project for production
        run: npm run build:prod

      - name: Deploy to Firebase Hosting (prod)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD_TRAILER_RENTAL }}
          channelId: live
          projectId: prod-trailer-rental

  build_and_deploy_test:
    if: github.event.pull_request.base.ref == 'test'
    runs-on: ubuntu-latest
    env:
      VITE_FIREBASE_API_KEY: 'AIzaSyACAGhDIIoyUXzvDUl0kRub9M887X6xjFM'
      VITE_FIREBASE_AUTH_DOMAIN: 'test-trailer-rental.firebaseapp.com'
      VITE_FIREBASE_PROJECT_ID: 'test-trailer-rental'
      VITE_FIREBASE_STORAGE_BUCKET: 'test-trailer-rental.appspot.com'
      VITE_FIREBASE_MESSAGING_SENDER_ID: '905721826645'
      VITE_FIREBASE_APP_ID: '1:905721826645:web:285f2311433141a0c7f3dc'
      VITE_FIREBASE_MEASUREMENT_ID: 'G-GKYYM2S35J'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project for test
        run: npm run build:test

      - name: Deploy to Firebase Hosting (test)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_TRAILER_RENTAL }}
          channelId: live
          projectId: test-trailer-rental
