name: Firebase Deployment

on:
  pull_request:
    branches:
      - main
      - test

jobs:
  build_and_deploy_prod:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_PROD }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_PROD }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_PROD }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET_PROD }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PROD }}
      VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_PROD }}
      VITE_FIREBASE_MEASUREMENT_ID: $${{ secrets.FIREBASE_MEASUREMENT_ID_PROD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project for production
        run: npm run build:prod

      - name: Deploy to Firebase Hosting (prod)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD_TRAILER_RENTAL }}
          channelId: live
          projectId: prod-trailer-rental

  build_and_deploy_test:
    if: github.event.pull_request.base.ref == 'test'
    runs-on: ubuntu-latest
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_TEST }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_TEST }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_TEST }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET_TEST }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID_TEST }}
      VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_TEST }}
      VITE_FIREBASE_MEASUREMENT_ID: $${{ secrets.FIREBASE_MEASUREMENT_ID_TEST }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project for test
        run: npm run build:test

      - name: Deploy to Firebase Hosting (test)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_TRAILER_RENTAL }}
          channelId: live
          projectId: test-trailer-rental
